config/routes.rb
Rails.application.routes.draw do
  root "pages#main"

  post "import_dictionary" => "dictionaries#import", as: :import_dictionary
  post "import_text" => "texts#import", as: :import_text

  get "download" => "pages#download", as: :download
  get "delete_all_records" => "pages#delete_all_records", as: :delete_all_records
end

app/models/dictionary.rb
class Dictionary < ActiveRecord::Base
  has_one :text

  def self.import(file)
    CSV.foreach(file.path) do |row|
      Dictionary.create(
        :word => row[0],
        :translation => row[1],
        :filename => row[2]
      )
    end
  end
end

app/models/text.rb
class Text < ActiveRecord::Base
  belongs_to :dictionary

  before_save :find_dictionary

  def self.import(file)
    Text.create(
      :content => File.read(file.path),
      :filename => file.original_filename
    )
  end

  def converted
    dic = self.dictionary
    return self.content.gsub(dic.word, dic.translation)
  end

  private

  def find_dictionary
    self.dictionary_id = Dictionary.find_by_filename(self.filename).id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  require 'csv'
end

app/controllers/dictionaries_controller.rb
class DictionariesController < ApplicationController
  def import
    Dictionary.import(params[:file])
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def main
    @dictionaries = Dictionary.all
    @texts = Text.all
  end

  def download
    texts = Text.all
    zip_file_name = "converted_files.zip"

    t = Tempfile.new("#{Time.now}")
    Zip::OutputStream.open(t.path) do |z|
      texts.each do |text|
        z.put_next_entry(text.filename)
        z.write(text.converted)
      end
    end
    send_file t.path, :type => 'application/zip',
                      :disposition => 'attachment',
                      :filename => zip_file_name
    t.close
  end

  def delete_all_records
    Dictionary.destroy_all
    Text.destroy_all
    redirect_to root_path
  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  def import
    respond_to do |format|
      Text.import(params[:files][0])
      format.json { render :json => { :status => 200 } }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dictionaries/_existing_table.html.slim
- if @dictionaries.any?

  table.table.table-striped
    thead
      tr
        th
          | Old
        th
          | New
        th
          | Filename

    tbody
      - @dictionaries.each do |dictionary|
        tr
          td
            = dictionary.word
          td
            = dictionary.translation
          td
            = dictionary.filename

app/views/dictionaries/_upload_dictionary.html.slim
h3
  | 1. Upload conversion table
h3
  small
    | Must be .csv file (columns: old, new, filename)

= form_tag import_dictionary_path, multipart: true do
  = file_field_tag :file
  br
  = submit_tag "Import", :class => "btn btn-primary"

app/views/layouts/_delete_all.html.slim
h3
  | 4. Delete all records

br

a.btn.btn-danger.btn-lg href="#{delete_all_records_path}" onclick="return confirm('Are you sure?')"
  | Delete

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CandraftConverter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/main.html.slim
.container
  .row
    .col-xs-12
      h1
        | Candraft Converter

  .row
    .col-xs-12.col-sm-4
      = render "dictionaries/upload_dictionary"

    .col-xs-12.col-sm-8
      = render "texts/upload_text"

  br

  .row
    .col-xs-12.col-sm-4
      = render "dictionaries/existing_table"

    .col-xs-12.col-sm-8
      = render "texts/existing_texts"

  .row
    .col-xs-12
      = render "texts/download"

  .row
    .col-xs-12
      = render "layouts/delete_all"

app/views/texts/_download.html.slim
h3
  | 3. Download converted files

br

a.btn.btn-warning.btn-lg href="#{download_path}"
  | Download

app/views/texts/_existing_texts.html.slim
- if @texts.any?

  table.table.table-striped
    thead
      tr
        th
          | File
        th
          | Preview

    tbody
      - @texts.each do |text|
        tr
          td
            = text.filename
          td
            = truncate(text.content, :length => 60)

app/views/texts/_upload_text.html.slim
css:
  .bar {
    height: 18px;
    background: green;
  }

h3
  | 2. Upload files to convert
h3
  small
    | All files need to be in .txt

input id="fileupload" type="file" name="files[]" data-url="#{import_text_path}" multiple=""

br

#progress.progress
  .bar.progress-bar style="width: 0%;"